Practical Implementation of Word Embedding 

In [24]:
from tensorflow.keras.preprocessing.text import one_hot

In [25]:
#Sentences

sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'yot videos are good']

In [26]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'yot videos are good']

In [27]:
#Define the vacab size
voc_size=10000

In [28]:
#Onehot Representation

one_hot_rep=[one_hot(words,voc_size)for words in sent]
one_hot_rep #giving that at what index we will be gtting '1'

[[7438, 414, 3082, 4516],
 [7438, 414, 3082, 9804],
 [7438, 1739, 3082, 5767],
 [8924, 7288, 223, 3356, 8740],
 [8924, 7288, 223, 3356, 4445],
 [6366, 7438, 6842, 3082, 5756],
 [5637, 2574, 3575, 3356]]

In [29]:
## Word embedding Representation

from tensorflow.keras.layers import Embedding,Flatten
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential 


In [30]:
import numpy as np

In [31]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length) # making the sentences of equal size 

print(embedded_docs)

[[   0    0    0    0 7438  414 3082 4516]
 [   0    0    0    0 7438  414 3082 9804]
 [   0    0    0    0 7438 1739 3082 5767]
 [   0    0    0 8924 7288  223 3356 8740]
 [   0    0    0 8924 7288  223 3356 4445]
 [   0    0    0 6366 7438 6842 3082 5756]
 [   0    0    0    0 5637 2574 3575 3356]]


In [32]:
# feature rep

dim=10


In [33]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [34]:

model.build(input_shape=(None, 8))

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs) # Every Word is represented by 10 dims

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step


array([[-0.0224479 ,  0.00301395, -0.00093174, -0.03572754, -0.04508265,
        -0.04760729,  0.0136433 ,  0.03638253,  0.00118638,  0.03727517,
        -0.0224479 ,  0.00301395, -0.00093174, -0.03572754, -0.04508265,
        -0.04760729,  0.0136433 ,  0.03638253,  0.00118638,  0.03727517,
        -0.0224479 ,  0.00301395, -0.00093174, -0.03572754, -0.04508265,
        -0.04760729,  0.0136433 ,  0.03638253,  0.00118638,  0.03727517,
        -0.0224479 ,  0.00301395, -0.00093174, -0.03572754, -0.04508265,
        -0.04760729,  0.0136433 ,  0.03638253,  0.00118638,  0.03727517,
         0.04695555, -0.04639974, -0.01584089,  0.02477881,  0.04976897,
         0.04800829, -0.03734609,  0.00954617,  0.02821184, -0.0406536 ,
        -0.00362555,  0.0325488 , -0.04630074,  0.01312256,  0.04125308,
        -0.00445281, -0.02438864,  0.04336491,  0.04680674,  0.04200221,
         0.006923  ,  0.04217071, -0.00629023, -0.02696902,  0.01738815,
         0.03954369,  0.04320184,  0.00526369, -0.0

In [17]:
# 1st sentence
embedded_docs[0]

array([   0,    0,    0,    0, 1612, 2759, 7057, 3122])

In [22]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step


array([[-0.0224479 ,  0.00301395, -0.00093174, -0.03572754, -0.04508265,
        -0.04760729,  0.0136433 ,  0.03638253,  0.00118638,  0.03727517,
        -0.0224479 ,  0.00301395, -0.00093174, -0.03572754, -0.04508265,
        -0.04760729,  0.0136433 ,  0.03638253,  0.00118638,  0.03727517,
        -0.0224479 ,  0.00301395, -0.00093174, -0.03572754, -0.04508265,
        -0.04760729,  0.0136433 ,  0.03638253,  0.00118638,  0.03727517,
        -0.0224479 ,  0.00301395, -0.00093174, -0.03572754, -0.04508265,
        -0.04760729,  0.0136433 ,  0.03638253,  0.00118638,  0.03727517,
         0.04695555, -0.04639974, -0.01584089,  0.02477881,  0.04976897,
         0.04800829, -0.03734609,  0.00954617,  0.02821184, -0.0406536 ,
        -0.00362555,  0.0325488 , -0.04630074,  0.01312256,  0.04125308,
        -0.00445281, -0.02438864,  0.04336491,  0.04680674,  0.04200221,
         0.006923  ,  0.04217071, -0.00629023, -0.02696902,  0.01738815,
         0.03954369,  0.04320184,  0.00526369, -0.0